{% set name = "docx-mailmerge" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docx-mailmerge-{{ version }}.tar.gz
  sha256: 6fbe353bd2f87dc6621d9add7bd04896181a469cc543502f1acc0c2444fd632a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - lxml
    - python >={{ python_min }}

test:
  imports:
    - mailmerge
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/Bouke/docx-mailmerge
  summary: Performs a Mail Merge on docx (Microsoft Office Word) files
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - yopiter
